### ISSUE TITLE
Implement the Hero Section for the collaborative website using HTML and CSS.

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#108]
#### Design:
Refer to the Figma design for the Hero Section. [Figma link](https://www.figma.com/file/lZ9dOTCeMYkxdyRtxCRH40/Untitled?type=design&node-id=0-1&mode=design)

#### Requirements:
1. Develop a responsive Hero Section using the design mentioned above.
2. Ensure compatibility across various devices and browsers.
3. Implement clean and maintainable HTML and CSS code.

#### Tasks:
1. write your code in `index.html` under the `hero-section` ID.
2. Apply the CSS styling in `hero-section.css` and import it in index.html based on the provided Figma design.
3. Ensure responsiveness for different screen sizes.

### Deadline:
[48 hours]

**Comment by rnavaneeth992** [comment]
Claim

**Comment by kushal7201** [comment]
Claim

**Comment by WadadParker** [comment]
Claim

**Comment by CodinJack** [comment]
claim

**Comment by Jarviss77** [comment]
Claim

**Comment by Rohit-110** [comment]
claim

**Comment by PranavBansal21** [comment]
Claim
