### ISSUE TITLE
Implement the Navbar

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#109]
# Implement the Navbar

## Description

We have a specific design for the website's Navbar, and your task is to implement it based on the provided Figma design. The design can be accessed at the following URL: [Figma Navbar Design](https://www.figma.com/file/lZ9dOTCeMYkxdyRtxCRH40/Untitled?node-id=0%3A3&mode=dev)

## Task Requirements

1. **Figma Design:** Refer to the provided Figma design to understand the visual elements and layout of the Navbar.
2. **HTML and CSS Implementation:** Implement the Navbar using HTML and CSS, ensuring it closely matches the design.
3. **Responsive Design:** Ensure that the Navbar is responsive and works well on various devices. **The navbar should be visible on the larger devices and it should become a hamburger menu on smaller devices.**
4. **Integration:** Integrate the implemented Navbar into the website codebase by putting it in **Navbar section in the index.html file** and **CSS in the css/navbar.css. file** 
5. **Hyperlinks**: Leave all the hyperlinks linked to a "/" only for now in Home, About Us etc. 

## Deadline

The deadline for submission is for **48 hours only**. The issue is bases on the FCFS policy

## Discussion
If you have any questions or need clarification on the Navbar requirements, please feel free to comment on this issue. We're here to help!

_Thank you for contributing to the Collaborative Web 2023 project. We look forward to seeing your implementation!
Happy coding!_

**Comment by vasusingla545** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
Claim

**Comment by Rohit-110** [comment]
claim

**Comment by AngadManroy** [comment]
Claim

**Comment by Talentedfalcon** [comment]
Claim

**Comment by Vishesh-Vijay** [comment]
@vasusingla545 You've been assigned this issue and you've got 48 hours to complete this task. Happy Coding!!!
