### ISSUE TITLE
Create the Figma design for the Mentors Section.

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#112]
#### Design:
1. Design a visually appealing Mentors Section in Figma.
2. Include an image placeholder for each mentor.
3. Add a clickable link or placeholder for linking to each mentor's profile.

You can refer to the homepage design which is available in the readme for color palette and overall design theme.
[Figma Link](https://www.figma.com/file/lZ9dOTCeMYkxdyRtxCRH40/Untitled?type=design&mode=design)

#### Requirements:
1. Ensure the design is aesthetically consistent with the overall theme of the collaborative web application.
2. Consider creating a grid layout or card-based design for displaying mentor information.
3. submit your design under `data/designs/mentors.json`

### Deadline:
[48 hours]

**Comment by sanju26honey** [comment]
Claim

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by WadadParker** [comment]
Claim

**Comment by Talentedfalcon** [comment]
Claim

**Comment by GammaMicrowave** [comment]
Issue assigned to @sanju26honey
