### ISSUE TITLE
Design the About us page

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#113]
# Design the About Us Page 

## Description

We want to create a captivating "About Us" page for the Collaborative Web 2023 website. The page should include details about Opencode'23, a button redirecting to the Opencode'23 GitHub page, and a countdown timer indicating the time left for Opencode'23 to end in days, hours, minutes, and seconds. The base design can be referenced from here [Figma URL](https://www.figma.com/file/lZ9dOTCeMYkxdyRtxCRH40/Untitled?node-id=0%3A1&mode=dev)

## Task Requirements

1. **About Opencode'23:** Include informative content about Opencode'23, highlighting its goals, achievements, and community spirit.
2. **GitHub Button:** Design and implement a button that redirects users to the Opencode'23 GitHub page when clicked.
3. **Countdown Timer:** Integrate a countdown timer displaying the time remaining for Opencode'23 to end in days, hours, minutes, and seconds.
4. **Integration**: Add the design in the data/designs/AboutUs.json file

## Deadline

The deadline for submission is for **48 hours only.** The issue is based on FCFS policy only

## Discussion

If you have any questions or need clarification on the "About Us" page requirements, please feel free to comment on this issue. We're here to help!

_Thank you for contributing to the Collaborative Web 2023 project. We look forward to seeing your creative design!
Happy designing!_

**Comment by CodinJack** [comment]
claim

**Comment by Jarviss77** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by Vishesh-Vijay** [comment]
@CodinJack You've been assigned this issue and you've 48 hours to complete this task!! Happy Designing!

**Comment by ajay484** [comment]
Claim
