### ISSUE TITLE
Implement the Mentor section on the website.

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#120]
### Summary
Create a new page for mentors section using HTML and CSS based on the design provided in the [Figma Mentor Page Design](https://www.figma.com/file/MNLO4eL2C3ySCrL7bkrQ7h/Untitled-(Copy)-(Copy)?type=design&node-id=0-1&mode=design&t=ao1XqHuC6Fqgjlvc-0).

### Requirements
1. Implement the HTML and CSS according to the provided Figma design.
2. Ensure responsiveness for various screen sizes.
3. Include placeholders for dynamic content (to be populated with real data later).
4. Write your html code inside the `mentor-section` in the `index.html`
5. add your CSS styles inside `css/mentors.css` and make sure that these styles only change for mentor section. For that you can add a prefix `#mentor-section` or whatever the id name of that section is.

**Comment by vasusingla545** [comment]
commit

**Comment by rnavaneeth992** [comment]
claim

**Comment by GammaMicrowave** [comment]
Issue assigned to @vasusingla545

**Comment by Vishesh-Vijay** [comment]
@vasusingla545 what's the update with the task?

**Comment by SharkyBytes** [comment]
Assign this to me I will complete it🫠

**Comment by vasusingla545** [comment]
there was a small issue. I will submit within half an hour
