### ISSUE TITLE
Implement the About Us page

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#121]
# Implement About Us Page

## Description

We have a specific design for the "About Us" page, and your task is to implement it based on the provided Figma design. The design can be accessed at the following URL: [Figma About Us Page Design](https://www.figma.com/file/O3aDV8V5KYZ0YmVp0hk43k/Untitled?type=design&node-id=0-1&mode=design&t=AfDBJAcvtNMkDCv1-0)

## Task Requirements

1. **Figma Design:** Refer to the provided Figma design to understand the visual elements, layout, and content structure of the "About Us" page.
2. **HTML and CSS Implementation:** Implement the "About Us" page using HTML and CSS, ensuring it closely matches the design.
3. **Responsive Design:** Ensure that the page is responsive and works well on various devices.
4. **Integration:** Integrate the implemented "About Us" page into the website codebase. The html code should be written in the about us section
5. **Timer**: For the timer, just create a similar element and put some static time into it. The actual implementation of timer will be a different task.

## Deadline

The deadline for submission is **48 hours only**. The task is based on FCFS policy.

## Discussion
If you have any questions or need clarification on the "About Us" page implementation requirements, please feel free to comment on this issue or ask on #collaborative-web channel on discord. We're here to help!

_Thank you for contributing to the Collaborative Web 2023 project. We look forward to seeing your implementation!
Happy coding!_

**Comment by vasusingla545** [comment]
claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by ssugam10** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by Vishesh-Vijay** [comment]
@vasusingla545 You've been already a task in this issue so this task is assigned to @rnavaneeth992. Keep us updated with your work. Happy coding !!!

**Comment by chiragmalik2612** [comment]
claim
