### ISSUE TITLE
Design the project section for the website.

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#122]
# Project Section Responsive Design

### Summary
Create a responsive design for the project section on the collaborative web page site. Refer to the mentors section design for inspiration, available [here](https://www.figma.com/file/MNLO4eL2C3ySCrL7bkrQ7h/Untitled-(Copy)-(Copy)?type=design&node-id=0-1&mode=design&t=ao1XqHuC6Fqgjlvc-0).

### Requirements
1. Implement a responsive design for the project section.
2. Use the mentor section design as inspiration, ensuring consistency in style and layout.

**Comment by kushal7201** [comment]
![Uploading image.png…]()

**Comment by Jarviss77** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by ssugam10** [comment]
claim

**Comment by chiragmalik2612** [comment]
claim

**Comment by Vishesh-Vijay** [comment]
@Jarviss77 You've been assigned this issue and you've 48 hours to complete this. Happy designing !!

**Comment by Vishesh-Vijay** [comment]
@Jarviss77 what's the update with the task?

**Comment by Jarviss77** [comment]
i am working on it , was busy with some other issue will submit by tommorow noon

**Comment by Vishesh-Vijay** [comment]
@Jarviss77 You only needed to design the page. Anyways, Just attach the Screenshot of the section that you implemented and if we find it good then i'll merge this PR. 
**Note: No extra points will be awarded for implementing too**

**Comment by Jarviss77** [comment]
> @Jarviss77 You only needed to design the page. Anyways, Just attach the Screenshot of the section that you implemented and if we find it good then i'll merge this PR. 
> **Note: No extra points will be awarded for implementing too**

It is written in the requirements to implement
anyways
