### ISSUE TITLE
Design the leaderboard section

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#124]
# Design the Leaderboard Section

## Description

We aim to showcase and recognize the contributions of our community members through a **Leaderboard** section on the Collaborative Web 2023 website. Your task is to design this section, highlighting top contributors, their achievements, and any relevant metrics.
You can take the reference from the homepage design of the website. **The figma design of the homepage is present in the README section of this repo.** 

## Task Requirements

1. **Design Elements:** Incorporate visually appealing elements to showcase the leaderboard, such as user avatars, achievement badges, and contribution statistics.
2. **Top Contributors:** Highlight the top contributors prominently, showcasing their profile pictures and usernames.
3. **Metrics:** Display relevant metrics, such as the number of contributions, lines of code written, or any other quantifiable contributions.
4. **Responsive Design:** Ensure that the "Leaderboard" section is responsive and works well on various devices.
5. **Integration**: Put up your figma design URL in the data/designs/leaderboard.json with your Github ID.

## Deadline

The deadline for submission is **48 hours only**. The task assignment is based on the FCFS policy

## Discussion

If you have any questions or need clarification on the "Leaderboard" section design requirements, please feel free to comment on this issue or on discord in the collaborative-web channel. We're here to help!

_Thank you for contributing to the Collaborative Web 2023 project. We look forward to seeing your creative design!
Happy designing!_

**Comment by chiragmalik2612** [comment]
claim

**Comment by CodinJack** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
claim

**Comment by Vishesh-Vijay** [comment]
@chiragmalik2612 You've been assigned this issue and you've 48 hours to complete this task. Happy designing!!

**Comment by chiragmalik2612** [comment]
@Vishesh-Vijay you may assign this issue to someone else.

**Comment by Rohit-110** [comment]
claim

**Comment by Vishesh-Vijay** [comment]
The task has been assigned to @Rohit-110 . Happy designing!

**Comment by Vishesh-Vijay** [comment]
@Rohit-110 What's the update with the task?
