### ISSUE TITLE
Implement the timer 

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#136]
# Implement the dynamic Timer 

## Description

We want to implement a dynamic timer whose design is already implemented, to the Collaborative Web 2023 website, displaying the time left for the event to finish in days, hours, minutes, and seconds. Your task is to implement this timer section, updating in real-time as the event progresses using javascript.

### Task Requirements

1. **Display Format:** Show the time left in days, hours, minutes, and seconds.
2. **Countdown:** The timer should count down towards the end of the event.
3. **Integration:** The js file required to be placed in js/timer.js file.

## Deadline
The deadline for submission is **48 hours only**. The task will be assigned on FCFS policy.

## Discussion
If you have any questions or need clarification on the dynamic timer section implementation requirements, please feel free to comment on this issue or on discord. We're here to help!

_Thank you for contributing to the Collaborative Web 2023 project. We look forward to seeing your implementation!_

**Comment by vasusingla545** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by PranavBansal21** [comment]
Claim

**Comment by Vishesh-Vijay** [comment]
@vasusingla545 You've been assigned this task and you've 48 hours to complete this task. Happy coding!!

**Comment by rnavaneeth992** [comment]
CLAIM

**Comment by sanju26honey** [comment]
Claim
