### ISSUE TITLE
Create the leaderboard section

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#142]
#  Create the Leaderboard Section 

## Description

We have a specific design for the Leaderboard section, and your task is to implement it based on the provided Figma design. The design can be accessed at the following URL: [Figma Leaderboard Design](https://www.figma.com/file/CSOsMCv7tueEAfnGMqZG45/Untitled?type=design&node-id=0-1&mode=design&t=6w0w9FBu7MLRsJq7-0)

## Task Requirements

1. **Figma Design:** Refer to the provided Figma design to understand the visual elements, layout, and content structure of the "Leaderboard" section.
2. **HTML and CSS Implementation:** Implement the "Leaderboard" section using HTML and CSS, ensuring it closely matches the design.
3. **Responsive Design:** Ensure that the section is responsive and works well on various devices.
4. **Integration**: Keep the html code in index.js inside the leaderboard section and the css in css/leaderboard.css. Don't forget to use the leaderboard id with every css you add in the file

## Deadline

The deadline for submission is **48 hours.** The task will be assigned on FCFS policy.

## Discussion

If you have any questions or need clarification on the Leaderboard section implementation requirements, please feel free to comment on this issue. We're here to help!

_Thank you for contributing to the Collaborative Web 2023 project. We look forward to seeing your implementation!
Happy coding!_

**Comment by vasusingla545** [comment]
claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by CodinJack** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by chiragmalik2612** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by Vishesh-Vijay** [comment]
@vasusingla545 you've been assigned this task and you've 48 hours to complete this task. Happy coding!

**Comment by abhisheksharma010** [comment]
Claim

**Comment by saisreesatyassss** [comment]
claim
