### ISSUE TITLE
Change the mentor section code to match project section and fill the data.

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#143]
## Issue Description
The current mentor section in our project lacks dynamic content and visually appealing cards. To improve user experience and engagement, we need to implement a dynamic mentor section with themed cards.

### Proposed Solution
Utilize the information present in `data/mentors.json` to dynamically generate mentor cards in the mentor section. The design of these cards should be similar to the themed cards present in the project section.

### Steps to Implement

1. **Reference from Project Section:**
   - Examine the existing themed cards in the project section to understand the design structure, layout, and styling.

2. **Data Source - mentors.json:**
   - Review the structure and content of `data/mentors.json` to understand the available information for each mentor.

3. **Dynamic Card Generation:**
   - Create a function or component that dynamically generates mentor cards based on the information provided in `mentors.json`.
   - Ensure that the design of these cards is consistent with the themed cards in the project section.

4. **Content Placement:**
   - Populate the mentor cards with relevant information from the `mentors.json` file, such as mentor name, expertise, and any other relevant details.

### Expected Outcome
A dynamic mentor section with visually appealing cards that are generated based on the information provided in `mentors.json`.

**Comment by CodinJack** [comment]
claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by PranavBansal21** [comment]
Claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by kushal7201** [comment]
Claim
