### ISSUE TITLE
Add Images for Projects

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#144]
## Description
We are looking to enhance our project documentation by adding relevant images for the projects mentioned in `data/projects.json`. This will improve the visual representation of our projects.

## Tasks
1. Review the projects listed in `data/projects.json`.
2. Find or create relevant images for each project.
3. Add the images to the `images` folder in this repository.
4. Update the paths in `data/projects.json` to point to the newly added images.

## Project List (from data/projects.json)
```json
{
  "projects": [
    {
      "image": "images/collaborative.jpg",
      "name": "Collaborative Web 2023",
      "description": "Opencode'23 Collaborative website!",
      "repo-url": "https://github.com/opencodeiiita/Collaborative-Web-2023/"
    },
    // Add more projects as needed
  ]
}

**Comment by Jarviss77** [comment]
claim

**Comment by abhisheksharma010** [comment]
Claim

**Comment by chiragmalik2612** [comment]
Claim

**Comment by rnavaneeth992** [comment]
Claim

**Comment by PranavBansal21** [comment]
Claim

**Comment by GammaMicrowave** [comment]
Issue assigned to @Jarviss77

**Comment by deepanshunegi06** [comment]
claim

**Comment by saisreesatyassss** [comment]
claim
