### ISSUE TITLE
Fix Background of the entire site

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#145]
Currenty their out some inconsistencies in the background of the whole site. Kindly fix this by editing the required css files available in `css` folder. You can also improve some styling if necessary.

**Comment by sarthakvermaa** [comment]
claim

**Comment by abhisheksharma010** [comment]
Claim

**Comment by PranavBansal21** [comment]
claim

**Comment by chiragmalik2612** [comment]
Claim

**Comment by GammaMicrowave** [comment]
Issue assigned to @abhisheksharma010

**Comment by sanju26honey** [comment]
Claim
