### ISSUE TITLE
Implement the background.

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#159]
add a grid background throught the entire site. You can take reference from the following video in order to complete your task. Make sure the grid is square and responsive for different sizes. All I need is if a certain tile is hovered I want its color to turn green for now and the layout should be similar to the video.

**Comment by Rohit-110** [comment]
Claim

**Comment by PranavBansal21** [comment]
Claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by chiragmalik2612** [comment]
claim

**Comment by sanju26honey** [comment]
Claim

**Comment by GammaMicrowave** [comment]
Kindly pull the changes @Rohit-110

**Comment by Pratik5252** [comment]
claim

**Comment by GammaMicrowave** [comment]
@Rohit-110 any updates
