### ISSUE TITLE
Fix minor issues in footer.

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#163]
![image](https://github.com/opencodeiiita/Collaborative-Web-2023/assets/98329292/12256169-469f-4d39-99c4-f4186e9c5de5)
Fix the logo of opencode and change the style @ 2023 OpenCode All rights reserved text make it fix at the bottom of the page

![image](https://github.com/opencodeiiita/Collaborative-Web-2023/assets/98329292/a1223a4d-17c6-400a-8f07-ba884a5d4aef)
Add icon to this move to the top button.

**Comment by abhisheksharma010** [comment]
Claim

**Comment by chiragmalik2612** [comment]
cl

**Comment by PranavBansal21** [comment]
Claim

**Comment by GammaMicrowave** [comment]
@abhisheksharma010 also fix the mobile styling of the footer I am increasing the points to 10 for this new addition in the issue.

**Comment by chiragmalik2612** [comment]
@GammaMicrowave  abhishek ko already ek issue assign h

**Comment by GammaMicrowave** [comment]
@chiragmalik2612 he already completed that issue, I forgot to close it sorry for inconvenience

**Comment by chiragmalik2612** [comment]
> @chiragmalik2612 he already completed that issue, I forgot to close it sorry for inconvenience

okk
