### ISSUE TITLE
Fetch the Project section data 

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#169]
# Fetch and Display Data on Projects Section

## Description

We have a "Projects" section on the Collaborative Web 2023 website, and your task is to fetch data from the `data/projects.json` file and dynamically display it within this section. The structure and styling of the section have already been implemented using HTML and CSS.

### Task Requirements

1. **Fetch Data:** Implement a mechanism to fetch data from the `data/projects.json` file.
2. **Dynamic Display:** Dynamically display the fetched data within the "Projects" section.
3. **Display Format:** Ensure the data is presented in a visually appealing and well-organized format.
4. **Responsive Design:** Ensure that the section remains responsive, adapting to different screen sizes.

### Deadline

The deadline for submission is **48 hours**. The task will be assigned on the basis of FCFS policy

### Discussion

If you have any questions or need clarification on the data fetching and dynamically showing, please feel free to comment on this issue or tag us on discord. We're here to help!

Thank you for contributing to the Collaborative Web 2023 project. We look forward to seeing your work!

Happy Coding!

**Comment by vasusingla545** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by Apoorv012** [comment]
claim

**Comment by Vishesh-Vijay** [comment]
The task has been assigned to @vasusingla545
