### ISSUE TITLE
Fetch the data for Leaderboard section

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#170]
# Fetch and Display Data on "Leaderboard" Section

# Description

We have a "Leaderboard" section on the Collaborative Web 2023 website, and your task is to fetch data from the provided API and dynamically display the top 10 contributors within this section. The structure and styling of the section have already been implemented using HTML and CSS.

## Task Requirements

1. **Fetch Data:** Implement a mechanism to fetch data from the provided API link using the `fetch` function (**don't use axios for it**).
2. **Top 10 Contributors:** Display only the top 10 contributors from the fetched data.
3. **Dynamic Display:** Dynamically display the top contributors within the "Leaderboard" section.
4. **Display Format:** Ensure the data is presented in a visually appealing and well-organized format.
5. **Responsive Design:** Ensure that the section remains responsive, adapting to different screen sizes.

## Deadline
The deadline for submission is **48 hours**. The task will be assigned on FCFS basis.

### Discussion

If you have any questions or need clarification on the dynamic fetching and displaying the leaderboard data, please feel free to comment on this issue or ping us on discord. We're here to help!

Thank you for contributing to the Collaborative Web 2023 project. We look forward to seeing your implementation!

Happy coding!

**Comment by Apoorv012** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by Vishesh-Vijay** [comment]
The task has been assigned to @Apoorv012
