### ISSUE TITLE
Update the Readme of the project

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#171]
# Update the Readme of the project

## Description 
You need to update the README of the collaborative-web-2023 repository and include all the necessary details about the project including all the design links that have been provided till now and all the API links. Also make it look attractive and appealing. For reference, you can go through different repositories of Opencode'23 and you may reference some other repository too.

## Deadline
The task deadline is for **48 hours.** If you've any doubt you may comment here or ping us on discord.

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
Claim

**Comment by Vishesh-Vijay** [comment]
The task has been assigned to @kushal7201

**Comment by Mannxxx** [comment]
Claim
