### ISSUE TITLE
small bugs

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#176]
make these 2 buttons represent the design of button similar to project section
![image](https://github.com/opencodeiiita/Collaborative-Web-2023/assets/98329292/a7feb18c-9a63-49c7-9dac-5da294cab7cc)
![image](https://github.com/opencodeiiita/Collaborative-Web-2023/assets/98329292/8fe39cd7-1f80-413a-a724-f5335dba38f7)

make it look like this button 
![image](https://github.com/opencodeiiita/Collaborative-Web-2023/assets/98329292/c6a7e8f7-c2e7-4871-97c5-d1caedd18c0d)

the other part of the task is to fix the navbar highlight on the section which is visible. It used to work before but somehow some lines got removed your task is to fix it again. It's js is already available in js folder just fix the small bug.

**Comment by Jarviss77** [comment]
Claim

**Comment by Pratik5252** [comment]
claim

**Comment by GammaMicrowave** [comment]
Issue assigned to @Jarviss77
