### ISSUE TITLE
Create and fetch Organizers details section.

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#178]
# Create and fetch Organizers details section.

## Description:
You are required to complete the organizers section in the index.html file in which you've to create a card for each organizer and also fetch the details from the `data/organizers.json` file and show it in that card. You need to use javascript for implementing the fetching part and no need to hard code the details.
- The section must be responsive.
- The card must contain all the details present in the file. You can take reference from the mentors card that has been already created.

## Deadline 
The deadline is of 2 days. 

## Discussion 
If you've any doubt or confusion you can comment here or ping us on discord

**Comment by vasusingla545** [comment]
Claim

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
claim

**Comment by rnavaneeth992** [comment]
Claim
