### ISSUE TITLE
Minor Bugs (1)

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#179]
# Minor Bugs (1)

## Description 
You are required to fix the following bugs:
- Change the display order of sections to `home>about>leaderboard>projects>oragnizers>mentors`.
- Give some padding to the about section so that it seems equally padded with other sections.
- Change the heading of the leaderboard section to **Top Contributors**

## Deadline 
The deadline is of 2 days.

## Discussion 
Feel free to comment here or ping us on discord if you've any doubt.

**Comment by CodinJack** [comment]
claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by Apoorv012** [comment]
claim

**Comment by Jarviss77** [comment]
claim

**Comment by kushal7201** [comment]
Claim
