### ISSUE TITLE
Minor Bugs (2)

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#180]
# Minor Bugs (2)

## Description
You are required to fix the following bugs :
- Improve the CSS of different cards that are present in the website. All the cards must look similar and you need to improve their styling. While changing the CSS of cards keep in mind the **responsiveness** of the section. The styling of card images must also bhi uniform in each and every card.
- The logo present in the footer is of low quality and it isn't looking good. So you need to change the Opencode logo of the footer section.

## Deadline
The deadline is of 2 days.

## Discussion
Feel free to comment here or ping us on discord if you've any doubt or confusion.

**Comment by rnavaneeth992** [comment]
claim

**Comment by Jarviss77** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by Parth4git** [comment]
claim
