### ISSUE TITLE
Add URL to "Get Started" Button and Improve "About Us" Section Styling

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#186]
#### 1. Add URL to "Get Started" Button

Currently, the "Get Started" button on the website lacks a direct link. To enhance user experience and direct new users to the OpenCode IIITA GitHub page, we should add a URL to the button.

#### 2. Improve "About Us" Section Styling

The "About Us" section needs styling adjustments to enhance its appeal and ensure consistency with the rest of the website. Both mobile and regular views should be addressed. Additionally, the section appears off-centered, and we need to correct its alignment.

**Comment by CodinJack** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by Mannxxx** [comment]
Claim
