### ISSUE TITLE
 Implement "Show More" Button for Mentor and Organizer Sections on Smaller Devices

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#187]
On smaller devices, such as mobiles, the current design of the website requires excessive scrolling to view all the cards in the Mentor and Organizer sections. To enhance user experience and optimize space, we propose implementing a "Show More" button that initially displays a limited number of cards (e.g., 6 cards), and upon clicking the button, reveals the remaining cards.

#### Proposed Solution

Introduce a "Show More" button for both the Mentor and Organizer sections. The button should be positioned after the initial set of cards (6 cards) and, when clicked, dynamically load and display the remaining cards.

### Additional Information

- **Screenshots:** [If applicable, include screenshots highlighting the current issues or proposed changes]

**Comment by Apoorv012** [comment]
claim

**Comment by Mannxxx** [comment]
Claim
