### ISSUE TITLE
Create the speaker section

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#196]
# Create the speaker section

## Descrption:
You need to create a speaker section in the collaborative website under the speaker section that has been initialised in the ```index.html``` file. The section must fulfill the following requirements:
-  The section must contain cards of different speakers.
-  The section must be responsive. 
-  The details of the speakers can be reference from this [link](https://opencode23.devfolio.co/speakers-judges).
-  The section must be present after the organiser section.
-  The section must contain a ```show more``` button which only works on this section.

## Deadline
The dealine for the task is 2 days.

## Discussion
You can tag us here or ping us on discord if you've any doubt or confusion.

**Comment by TheDivineAurora** [comment]
claim

**Comment by Apoorv012** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by Vishesh-Vijay** [comment]
@TheDivineAurora you've been assigned this task

**Comment by Vishesh-Vijay** [comment]
@TheDivineAurora what's the update?

**Comment by TheDivineAurora** [comment]
will submit pr by tmrw noon

**Comment by Vishesh-Vijay** [comment]
@TheDivineAurora update me with this PR till 11.30 pm or I'll open this task for claim again

**Comment by TheDivineAurora** [comment]
Please give me 2 hrs time .. ill make a pr
