### ISSUE TITLE
Create the Events section

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#197]
# Create the Events section

## Description
An event section has been initalized in the ```index.html``` file. You need to complete the section. It should fulfill the following requirements:
- The section must contain cards of different events that have been conducted/are being conducted in the Opencode '23 like Codeguerra, Data-Blitz etc.
- The section must be responsive.
- The data and information required for these events can be found on **Discord** announcements of Opencode'23/**Instagram** handle of Geekhaven.
- The CSS of cards must match with the background.

## Deadline
You must complete the task in 2 days.

## Discussions
You can tag us here or ping us on discord for any doubts or confusion.

**Comment by TheDivineAurora** [comment]
claim

**Comment by Apoorv012** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by Apoorv012** [comment]
claim

**Comment by Jarviss77** [comment]
claim

**Comment by Rohit-110** [comment]
Claim

**Comment by Vishesh-Vijay** [comment]
@TheDivineAurora you've been already assigned as issue in this repository so this task is assigned to @Apoorv012

**Comment by Vishesh-Vijay** [comment]
@Apoorv012 what's the update?

**Comment by Apoorv012** [comment]
Few hours
