### ISSUE TITLE
Improve the Responsive styling

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#199]
# Improve the responsive styling of the website

## Description
Improve the styling of the website **in the mobile view.** The following are the requirements for this task:
- The **opencode** text and the hamburger menu in the navbar are not aligned properly with each other. This needs to be fixed.
- There is very less margin between the landing section and the about us section
- The landing section must contain the logo and the **get started** button only in the center of the page and give margins to both the landing and the about us section
- On the landing section which contains the logo and the **get started** button, the alignment of both the components is not correct. Fix it.
- The about us section content must be aligned to the center of the website.

## Deadline
You've 2 days to complete this task

## Discussion
Feel free to tag us here or ping us on discord if you've any doubt or confusion.

**Comment by kushal7201** [comment]
Claim
