### ISSUE TITLE
Project.json Completion Issue

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#2]
# Project.json Completion Issue

## Description

We have initiated the creation of a `project.json` file inside the `data` folder in the root directory of our OpenCode'23 project. The purpose of this file is to consolidate information about various projects within OpenCode'23. Your task is to complete the `project.json` file by adding entries for each project following the provided template.

## Template for Project Entry

```json
{
    "name": "Collaborative-Web-2023",
    "description": "Opencode'23 Collaborative website!",
    "repo-url": "https://github.com/opencodeiiita/Collaborative-Web-2023/"
}
```

_Feel free to ask any queries on discord_

**The deadline for the issue is 48 hours**

**Comment by Ashutosh9993** [comment]
Claim

**Comment by Vishesh-Vijay** [comment]
assigned to @Ashutosh9993 . Keep up your work !

**Comment by PranavBansal21** [comment]
claim

**Comment by vineeshmittal1** [comment]
claim

**Comment by Murdock9803** [comment]
Claim. Would like to work on this issue if available.

**Comment by optimus-pride** [comment]
claim

**Comment by vasusingla545** [comment]
claim

**Comment by AshAhmad2022** [comment]
Claim

**Comment by GammaMicrowave** [comment]
@Ashutosh9993 can you provide any updates on the following issue? might better if you update us on the status on discord.

**Comment by Hannah2k23** [comment]
Claim

**Comment by Reene-Simon** [comment]
Claim

**Comment by Vedant2379** [comment]
claim

**Comment by InnocentSinner08** [comment]
claim

**Comment by Vishesh-Vijay** [comment]
Dear @Ashutosh9993 You have till tonight to complete this issue or it will be assigned to someone else. Kindly update us with the PR status.

**Comment by Vishesh-Vijay** [comment]
Due to inactivity on this issue by the assigned person, The issue is open for claiming again!! The issue will be assigned on FCFS policy

**Comment by rnavaneeth992** [comment]
claim

**Comment by Hannah2k23** [comment]
Claim

**Comment by kushal7201** [comment]
claim

**Comment by Luckydhingra** [comment]
claim

**Comment by Vishesh-Vijay** [comment]
The issue is now assigned to @rnavaneeth992!!

**Comment by ajay484** [comment]
Claim. I want to work on this issue.

**Comment by meAyushSharma** [comment]
Claim. I want to work on this issue

**Comment by k7aditya** [comment]
claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by rnavaneeth992** [comment]
I wrongly unassigned
Please assign it
claim
I will complete it as soon as possible
