### ISSUE TITLE
Improving responsive styling (2)

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#202]
# Improving responsive styling

## Description 
The following styling needs to be improved in the mobile version of the website:
- The heading, text and button in the about us section is not aligned to the center. It needs to be shown on the center of the page.

![IMG_20240107_232802.jpg](https://github.com/opencodeiiita/Collaborative-Web-2023/assets/97442257/12031a80-aa02-4602-9795-67485a750319)

- The headings like top contributors need to have more padding.
- The navigation list that opens up after clicking on the hamburger menu is not styled properly. Fix it

## Deadline
The task needs to be completed in 2 days.

## Discussion
Feel free to tag us here or ping us on discord if you've any doubts or confusions.

**Comment by rnavaneeth992** [comment]
claim
