### ISSUE TITLE
Implementing show more button

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#203]
# Implementing show more button

## Description
The show more buttons present in the website in sections like projects, organisers and mentors don't work in mobile view. You need to implement a logic in javascript so that initially it only shows 5 cards for each section and after clicking on the show more button, the complete list is shown.

## Deadline
The task needs to be completed in 2 days.

## Discussion
Feel free to tag us here or ping us on discord if you've any doubts or confusions.

**Comment by Apoorv012** [comment]
c

**Comment by Mannxxx** [comment]
claim

**Comment by Apoorv012** [comment]
I am mostly done
