### ISSUE TITLE
Enhancements to User Experience

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#208]
### Description

Our website currently lacks some key user experience enhancements that we want to address to improve overall usability and engagement.

### Tasks

1. **Staggered Animation Delay on Cards:**
   - Implement a staggered animation delay on the cards to create a visually appealing entrance effect.

2. **Smooth Scroll on Navbar Click:**
   - Add smooth scrolling behavior when users click on the navbar links for a seamless transition between sections.

#### Details

- **Location**: Cards section of the website.
- **Animation Type**: Staggered entrance animation with a smooth transition.
- **Delay**: Add a delay to each card, creating a staggered effect.

#### Example Code

```css
/* Example CSS code for staggered animation delay */
.card {
  opacity: 0;
  transform: translateY(20px);
  transition: opacity 0.5s ease, transform 0.5s ease;
}

.card:nth-child(odd) {
  animation-delay: 0.2s; /* Adjust delay based on desired stagger effect */
}

.card:nth-child(even) {
  animation-delay: 0.4s; /* Adjust delay based on desired stagger effect */
}

.card.animate {
  opacity: 1;
  transform: translateY(0);
}

**Comment by rnavaneeth992** [comment]
claim

**Comment by Mannxxx** [comment]
claim
