### ISSUE TITLE
Create Design for the homepage of Collaborative-Web

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#22]
## Objective

Create an innovative home page for Collaborative Web showcasing your creativity and design skills.

## Guidelines

- **OpenCode Branding:** Prominently feature the OpenCode logo and name.
- **Creativity Encouraged:** Experiment with colors, layouts, and unique visual elements.
- **Responsive Design:** Ensure compatibility with desktop, tablet, and mobile devices.

## Submission Instructions

1. Fork the repository.
2. Submit your figma link in the designsjson which is availablel in `data/designs/homepage.json`
3. Add your entry in the following format:-
```json
[
  {
    "GitHubId": "your_github_id",
    "figmaURL": "your_figma_url"
  }
]
```

## Evaluation and Rewards

- Designs will be judged on creativity, usability, and adherence to brand guidelines.
- The winning design will be implemented on the Collaborative Web home page.
- Top 3 designs would recieve the following points respectively
     **1. 30 points
     2. 25 points
     3. 20 points**

**Submission Deadline: [48 Hours]**

Get ready to unleash your creativity! 🎨💻

**Comment by PranavBansal21** [comment]
claim

**Comment by Nandinig24** [comment]
claim

**Comment by optimus-pride** [comment]
claim

**Comment by Nivedh-Biju** [comment]
claim

**Comment by kushal7201** [comment]
I want to claim the issue @GammaMicrowave

**Comment by GammaMicrowave** [comment]
No need to claim this issue. Just make your design and submit it in the required file. We would award points to the top 3 designs.

**Comment by Nandinig24** [comment]
PLEASe provide logo of opencode
