### ISSUE TITLE
Creater a footer for the main site

### ISSUE THREAD

**Issue by GammaMicrowave** [opencodeiiita/Collaborative-Web-2023#62]
Kindly create a footer for the collaborative web website. Make sure to include these following things in the footer:-
1. **IIITA and GeekHaven Logos**
2. **OpenCode Social Media Links**
3. **OpenCode Logo**

### Additional Information
- Please ensure that the design is responsive and works well on various screen sizes.
- Verify that all logos and links are correctly linked to their respective destinations.

### Deadline
Kindly complete this issue under 48 hours.

### Related Files
- `index.html` (under the footer section specified.)
- `footer.css` (create this files under `css/footer.css`)

### Screenshots (if applicable)
[Attach any relevant screenshots or mockups to illustrate your work on discord if needed.]

Thank you for your collaboration in improving the project's design! 🚀

**Comment by shrutikarathi6** [comment]
claim

**Comment by optimus-pride** [comment]
Claim

**Comment by CodinJack** [comment]
claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by atharva0192** [comment]
claim

**Comment by vasusingla545** [comment]
claim

**Comment by GammaMicrowave** [comment]
The issue is assigned to @shrutikarathi6 Best of luck!

**Comment by Nandinig24** [comment]
Claim

**Comment by rnavaneeth992** [comment]
Claim

**Comment by shrutikarathi6** [comment]
@GammaMicrowave can I get color palette for footer

**Comment by GammaMicrowave** [comment]
You can take colors from the banner image for now
Just try to use make some css variables and use them as your colors instead of writing colors directly. I would suggest making 3-4 color variables like background, main-color, accent-color etc. As we have not decided on a color palette yet later when we need to change the color we would just have to update these colors. For more queries you can ask us on discord in our #collaborative-web channel

**Comment by shrutikarathi6** [comment]
@GammaMicrowave Do I need to make changes???

**Comment by meAyushSharma** [comment]
Claim. I wish to work on it, sir.

**Comment by shrutikarathi6** [comment]
![Screenshot 2023-12-15 230215](https://github.com/opencodeiiita/Collaborative-Web-2023/assets/122254552/1d782d12-8612-4b01-9a7f-f5246cb6a20c)

**Comment by meAyushSharma** [comment]
Got it. Thank you for informing me, Sir.
