### ISSUE TITLE
Create a 'Move-To-Top' Button 

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#63]
# Implement "Move to Top" Button

## Issue Description

We want to enhance the user experience on the Collaborative Web 2023 website by adding a "Move to Top" button. This button should float on the bottom right side of the page and become visible when users scroll down the page. When clicked, it should smoothly scroll the user to the top of the page.

## Task Requirements

1. **Floating Button:** The "Move to Top" button should be a circular element floating on the bottom right side of the page.
2. **Icon:** Inside the circular button, include a top-pointing arrow to indicate the "move to top" action.
3. **Visibility:** The button should become visible only when the user scrolls down the page.
4. **Smooth Scroll:** Implement a smooth scroll effect when the button is clicked, ensuring a seamless user experience.

### Deadline

The deadline for submission is **48 hours**. The issue is based on FCFS policy.
### Discussion

If you have any questions or need clarification on the implementation requirements, please feel free to comment on this issue or contact us on the #collaborative-web channel. We're here to help!

_Thank you for contributing to the Collaborative Web 2023 project. We look forward to seeing your implementation!_
_Happy coding!_

**Comment by CodinJack** [comment]
claim

**Comment by atharva0192** [comment]
claim

**Comment by PranavBansal21** [comment]
claim

**Comment by Nandinig24** [comment]
claim

**Comment by ShauryaJain03** [comment]
claim

**Comment by QuantTitan** [comment]
claim

**Comment by vasusingla545** [comment]
claim

**Comment by Vishesh-Vijay** [comment]
The issue has been assigned to @CodinJack . You have 48 hours to complete this task. Happy Coding!!

**Comment by rnavaneeth992** [comment]
Claim

**Comment by InnocentSinner08** [comment]
Claim

**Comment by shahswati098** [comment]
claim

**Comment by Tulsi5990** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by meAyushSharma** [comment]
Claim. I want to work on it.
