### ISSUE TITLE
Add favicon to the website

### ISSUE THREAD

**Issue by Vishesh-Vijay** [opencodeiiita/Collaborative-Web-2023#94]
# Add Favicon to the Website

## Description

We want to improve the branding of the Collaborative Web 2023 website by adding a favicon. A favicon is a small icon that appears in the browser tab, bookmarks, and other areas. Your task is to create and implement a favicon that represents the essence of the project.

### Task Requirements

1. **Favicon Design:** Design a favicon that reflects the theme and purpose of the Collaborative Web 2023 project.
2. **File Format:** Provide the favicon in a standard format such as ICO, PNG, or SVG.
3. **Implementation:** Integrate the favicon into the website so that it appears in browser tabs and bookmarks.

### Deadline

The deadline for submission is **48 hours**.The issue is bases on FCFS policy.

### Discussion

If you have any questions or need clarification on the favicon requirements, please feel free to comment on this issue. We're here to help!

_Thank you for contributing to the Collaborative Web 2023 project. We look forward to seeing your creative favicon!_
_Happy designing!_

**Comment by rnavaneeth992** [comment]
claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by QuantTitan** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by atharva0192** [comment]
claim

**Comment by GovindaRohith** [comment]
Claim

**Comment by Nandinig24** [comment]
Claim

**Comment by AngadManroy** [comment]
Claim

**Comment by PranavBansal21** [comment]
Claim

**Comment by Nandinig24** [comment]
Claim

**Comment by k7aditya** [comment]
claim

**Comment by Vishesh-Vijay** [comment]
@rnavaneeth992 You already have an assigned issue in this repo so I can't assign this issue to you.
@QuantTitan this issue is assigned to you and you've 48 hrs to complete this. Happy coding !!

**Comment by ajay484** [comment]
Claim

**Comment by Aakash-1801** [comment]
claim

**Comment by Vishesh-Vijay** [comment]
@QuantTitan What's the update with the task?

**Comment by QuantTitan** [comment]
> @QuantTitan What's the update with the task?

Hey @Vishesh-Vijay I am currently finishing another task assigned to me, I will start working on the issue soon

**Comment by Vishesh-Vijay** [comment]
@QuantTitan 12 am is the deadline for the issue.Kindly update us with your progress

**Comment by PranavBansal21** [comment]
claim

**Comment by GammaMicrowave** [comment]
Due to inactivity of previous assignee I am reopening this issue.

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by GammaMicrowave** [comment]
Since kushal claimed it first I am assigning it to him. Others can wait till night I would try to post some more issues by then.
